### ISSUE TITLE
Docs build is failing

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#303] opened 2020-09-17 06:58 UTC
## How to Reproduce
https://github.com/OpenMined/PyDP/runs/1097568856

**Comment by BenjaminDev** [comment] 2020-10-02 18:23
I believe the issue is in build_PyDP.sh:
```
#!/bin/bash
pipenv install --dev --skip-lock
bazel coverage src/python:bindings_test --verbose_failures # THIS LINE needs to specify the config to use 
find ./ -name _pydp.so -print0 | xargs -0 -I {} rm {}
cp -f ./bazel-bin/src/bindings/_pydp.so ./pydp
```
So we need to update it to:
```
#!/bin/bash
pipenv install --dev --skip-lock
bazel build --config Linux src/python:bindings_test  --verbose_failures
find ./ -name _pydp.so -print0 | xargs -0 -I {} rm {}
cp -f ./bazel-bin/src/bindings/_pydp.so ./pydp
```

**Comment by BrendanSchell** [comment] 2020-10-06 17:55
@chinmayshah99 this can be closed now I think since it should be resolved by #306

**Closed as completed** 2020-10-06 20:30 UTC
Labels: Type: Bug :bug:, Status: Available :wave:, Hacktoberfest
